# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.1.0/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/invakid404/fags.ts
          tag: master@sha256:80400685087608307969d320d815a9af23733224ff388d299dfd5987d5da9cf7
        envFrom:
          - secretRef:
              name: fagsts

defaultPodOptions:
  imagePullSecrets:
    - name: docker-config

service:
  main:
    controller: main
    ports:
      http:
        port: 3000

ingress:
  main:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/funnel: "true"
      tailscale.com/hostname: fagsts
    hosts:
      - host: fagsts.${TAILSCALE_DOMAIN}
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - fagsts.${TAILSCALE_DOMAIN}
