apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: all
spec:
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: all
        spec:
          postRenderers:
            - kustomize:
                patches:
                  - patch: |-
                      apiVersion: networking.k8s.io/v1
                      kind: Ingress
                      metadata:
                        labels:
                          tailscale.com/proxy-class: "default"
                        name: all
                    target: 
                      kind: Ingress
      target:
        group: helm.toolkit.fluxcd.io
        version: v2beta1
        kind: HelmRelease
