apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: mosquitto
    namespace: apps
    files:
      - mosquitto.conf=./mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true
