apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: minio
      version: "12.13.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10

  values:
    auth:
      existingSecret: minio-creds

    persistence:
      enabled: true
      existingClaim: minio-data

    ingress:
      enabled: true
      ingressClassName: tailscale
      annotations:
        tailscale.com/hostname: minio-console
      hostname: &console-host minio-console.${TAILSCALE_DOMAIN}
      extraTls:
        - hosts:
            - *console-host

    apiIngress:
      enabled: true
      ingressClassName: tailscale
      annotations:
        tailscale.com/hostname: minio
        tailscale.com/funnel: "true"
      hostname: &api-host minio.${TAILSCALE_DOMAIN}
      extraTls:
        - hosts:
            - *api-host

    nodeSelector:
      iscsi: "true"
