apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: synology-csi-retain
