---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plex
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: core
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/plex
              tag: 1.42.2
            env:
              TZ: ${TIMEZONE}
              PUID: ${SQUASH_UID}
              PGID: ${SQUASH_UID}
              PLEX_ADVERTISE_URL: https://${PLEX_IP}:32400,https://plex.${TAILSCALE_DOMAIN}:443

    service:
      main:
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${PLEX_IP}"
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        className: tailscale
        annotations:
          tailscale.com/hostname: *app
          tailscale.com/funnel: "true"
        hosts:
          - host: &host plex.${TAILSCALE_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: *app

      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/torrents
        globalMounts:
          - path: /mnt/media

      transcode:
        enabled: true
        type: emptyDir

    defaultPodOptions:
      nodeSelector:
        metallb-l2: "true"
      dnsConfig:
        options:
          - name: ndots
            value: "1"
