---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app plex
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: core
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            env:
              PLEX_ADVERTISE_URL: https://${PLEX_IP}:32400,https://plex.${TAILSCALE_DOMAIN}:443
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.40.2.8395-c67dce28e@sha256:13c3727ed0cafb34cd861bb4a2f3e1e1911aef1f56777f41c185fefef305787f

    service:
      main:
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${PLEX_IP}"
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        className: tailscale
        annotations:
          tailscale.com/hostname: *app
          tailscale.com/funnel: "true"
        hosts:
          - host: &host plex.${TAILSCALE_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: *app

      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/torrents
        globalMounts:
          - path: /mnt/media

      transcode:
        enabled: true
        type: emptyDir

    defaultPodOptions:
      runtimeClassName: nvidia
      dnsConfig:
        options:
          - name: ndots
            value: "1"
