# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.1.0/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/invakid404/mergedoc
          tag: latest@sha256:9b22b6a0d9cd4adb865d8e03a94eb0f263f7b16c26460652d61fa3807a13d1bf
        envFrom:
          - secretRef:
              name: mergedoc

defaultPodOptions:
  annotations:
    reloader.stakater.com/auto: "true"
  imagePullSecrets:
    - name: docker-config

service:
  main:
    controller: main
    ports:
      http:
        port: 3000

ingress:
  main:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/hostname: mergedoc
    hosts:
      - host: mergedoc.${TAILSCALE_DOMAIN}
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - mergedoc.${TAILSCALE_DOMAIN}
