apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: invapaste
    namespace: apps
stringData:
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6Qr8puoC7N7hk/K06uoVH427ECSffXe18QW6+n0pS3A=,iv:lX8b3KEql1p/VppSkKA3vER//L8L40LW6FQFWbQOU+8=,tag:fEQtldm3XXkbxsBYf44eYw==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:5kCfj7oVQcNRJXP0AYeS2w==,iv:Irmh9nZUOP93BtrmOMnCKIB+TYSR8+ZmyWpssOleqZY=,tag:OnYTvhZQ0OLnu6qieWNWcA==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:MuGi22B7nQlLdkpULTLf2jpbCaFVsWnHz4CeEiTzT+J6,iv:dRdMiuRTgaATHjYS08f49oKz9AvsB7WP/RcMIg2ZqpA=,tag:9VKpFNQNNkmbvmtYVD3e1Q==,type:str]
    S3_ENABLE_SSL: ENC[AES256_GCM,data:k4PD7PA=,iv:6o87HB6rx0EMc1MvU/TyRnUVxxp41kd0meUvpRJAAyU=,tag:Ge8IH+M4Phq1s6hTemAtpQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:b/qjZ9A+nUjpQKwY+WbnpC0y4C/s3Ips,iv:zAJ2wEGmjwXTRgE0TquwMv1eD/SV6dl/wMoxiBCVdrI=,tag:S30KyapwsQMFIYfRHB0xtw==,type:str]
    PUBLIC_URL: ENC[AES256_GCM,data:oRuqWWjJlWrRrcQf9AGkK+txC1yQcg==,iv:bzSoqdxs5LzNXnYV/UasNvHaoru5qMDzsCbKZaHngmg=,tag:PsoFk64xxWjYODwQGAvu3A==,type:str]
    WINDMILL_BASE_URL: ENC[AES256_GCM,data:s7VwOwPeb9O0TwG8imtvJQGqCR2DcHyqZFIqsdj5BKXZfxa9,iv:22RpvEEO8kHjsmUvSo44L+DI1ZsbtvcpVUSBjxx7SgE=,tag:Cq/jquO/DApp7X4PQBq9Lg==,type:str]
    WINDMILL_TOKEN: ENC[AES256_GCM,data:siJZllE8ypQhZX27g+zIcsww82jKXFpLsDCQDAlE,iv:D0ty6JaGSHf31XTxRolKmnMTw3EeYQIBQ0OK4lccNQA=,tag:np4W34UyKi0vswJDt/rRlw==,type:str]
    WINDMILL_WORKSPACE: ENC[AES256_GCM,data:LwQ7ScYYNMIGIZo=,iv:I/IXOpRgf5iQFuqhwupbxQA7WVQS+WiFlveN8uesmH0=,tag:XdgtfCLgMzNplXPYoKjakQ==,type:str]
    WINDMILL_AI_RESOURCE: ENC[AES256_GCM,data:EmorErArv2iTbWUuotpMQx8/j1ScwffEFDg=,iv:lyepueodn87UIG2nbW0DMEfHQxi5igKksb90eA6VLbk=,tag:LG6HXFeIoo/umF3BXyfleA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-19T14:23:59Z"
    mac: ENC[AES256_GCM,data:FI2u8/aW8taVeZ44/hkC9Sf5DlveciRnhvseuVvPe1Af3DR1TJ7PmTPw4QdGsfLWKYVQmwm4Ey+V/ls6vRadH8syG+bcXBErF74TPTV/NVVrDpfiLeZjf8FkJz52klQTMyOgEiArPCyAaJQ6aJsHWDr4gH88Tl12m9vXNrMV1oc=,iv:QlNsU7lacRcqtjkvny09mCuJhXahPCehCg07zO8xfYQ=,tag:MABJN2A+SRdKxgyTdjD1xA==,type:str]
    pgp:
        - created_at: "2024-04-24T10:29:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ/+PHdQ2tE5xYZ8fxXew30+Xw7/B/hcCJ2iEtnk6yImIb42
            GxoTE5rseCF5sc6t0/iLTzen80xgBT6bNOXsfr8nI3KxtmlEfJr0t4b46zA3WAXn
            YnMhPTRPbQmdjBaYIDUUNFejtzQ1f2hsA9kDYSuO6cA0u++y3Gy4BrlZ4hOWwF38
            5uEXxa/z+L0erl6fkiR0b36ESz+MClrPkI/2L7udRvbI2qMX40EV9okYg7tGvhC0
            nkQBq/9iLyVLr8OJUE0UZCmfvBiPd86CAlYHs0LxpPAY6o32ISoktT4olgIvLfAO
            jxBZjrwL5RGhOMpAyskl7mSrprm1IXWgXcyPpJZv3b9ePAzc42/kbwjnF/LrypN3
            A5zxIcPUt2f0sGlxeS8748LPqwt6GIk8IIog04+fN8mvqegz10GzaI6bJhmL6qeB
            aUCZnYHAOrMV+kCnR49OxP0w92p32D8K+AqZGjkwNJhx0svZMF+A77bfurTVSOf3
            L3bv572C6E0EQWdO+OghYeKEBvfeuK5LnDucJFvbj/3l0XqJva07YbUxR6Anw9ER
            ZNZoLIoVg+n12Jg8E81qvR/uwHVBHzsj6VAMbjT5WcMCBnSRU8s6ImP4pjctDXle
            xiAMBkUyDSNhNLVpoPVuZ1sTvr1W2cf+fHgzYNRH3hfgROntBdNQmcoBnBQDp63S
            XgHDTCBzV90YLRu0o/NtNdQIfuv3zlwXLNZpcipQ2IcJBn2Q/rOsrcYZhHtNeEUr
            saHnFhw7cJR0woJcwbQ8Uc+6BYbffL680BSXPzNrtr9i/5WDZG/lLNncVwO4shg=
            =AiDA
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
