apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: postgresql
      version: "13.2.29"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: postgres

    global:
      postgresql:
        auth:
          postgresPassword: ${POSTGRES_PASSWORD}

    primary:
      service:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: postgres
      persistence:
        enabled: true
        existingClaim: postgres-data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - styx
      startupProbe:
        enabled: true
        failureThreshold: 60
        periodSeconds: 30
