apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: lowrider-db
    namespace: core
stringData:
    password: ENC[AES256_GCM,data:yG8GibU/bTekxiEfplrAnmRvCYt/AVkJAfdm+cwJDVzVglqsTfCKGW2ew12aK0DT,iv:vmPebd/PHJh59BfGjC8xtReQxi+Zvb4t0pj2p7izIOw=,tag:4vWCsgsgzPNzTDwV+2H/DQ==,type:str]
sops:
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-12T18:42:05Z"
    mac: ENC[AES256_GCM,data:MFpIMBfitVl0bPi796j7th+j0BFBRIeRm0UjLI5vQKRU48COT5L2kwhliUTzXReYncET4T8n1D7OCHonsS0VHUBehp/pxweRn2m6AxB2D/O6GNt26JdlhaC0H/L9QbjrcJD8eZjXPxjB3B6nZawN1R52ccdA/yLO1yI3Ki7F2WY=,iv:4PUKGKl3C0Ys5Qu86A8+FjRTBaNOb7gUCGKzCXI4etg=,tag:YLFR0miFRctIX+KQm4WH1g==,type:str]
    pgp:
        - created_at: "2026-08-12T18:42:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ//SSLEN1HltpDp8Xqr8mOetOy1IxxdzyMpUGFQsK5Trx5j
            tIxn0EO4BAz8DmgCvcQzReDJhh39pE3qq4kOcUdmN7pk252rbCE8/+XfaQmtnK8/
            PeEmYRJ4MTCOrkUe4KlgA09P1xiBFBwPTOq+vrNlV9txF6g/umM5NBVeieOeNCiy
            pjbg1Yn6Xm7wnGfOkHGuLbIkIeHmM6C0VW6Oy0ARM6FtxomBkHRmLQkc9Zy9zW88
            S6576nVxVcqZq0gFUzVcsQz6VFQZtFXucqtZDn/WaCCJng/yMd97dErGft7yEdyF
            e8oQt1WZt4W5ZLTqS4zctpA6c2orRN+AdwfVDFGZqqGrxA0C1iLKEPSHsvq7M/09
            z2LpAH6tBb5KAlE6o+PN54lQLN5cW++XdntnuXJOuNCR5LhaKFPa5SHgleGgAWMR
            DnESEnMJRCzZedFAN/QYNEO4ZPjv1MWQadvuDD1vpcpCkLz45auSH76RtkasEkOd
            Odmbk0CtEb86olK5DghYn3BXbt+x0aMcX29Bapq9aXOL1HiEkcY6LoiCDrZYoPvb
            ZEbI5Y4WzlI8NiiGudhLJ34MIewkVFPgzWNGj2Gz21jOmJVfvCaOoyFyQV7Bxe6L
            zak/Qa9iVQL3HNkedqKtU25dVjPwv/cqZ6TRuaYgr3YZQROr65ZPlbBUeKKXrsPS
            XgGpON3QzWqg+7vADLpT8LeNzyOvZISsAse8uA8Tj/RATGKj7Oxf75/YpCriSFhm
            P15K50semuaHEbO8LemWDvQhl6inHs+pm9Zzj1nDzLESoeZ5Gg4URNtVO9w74dA=
            =5bNY
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    version: 3.13.3
