apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./base.yaml
  - ./metallb.yaml
  - ./ip-pools.yaml
  - ./postgres.yaml
  - ./reloader.yaml
  - ./tailscale-operator.yaml
  - ./tailscale-config.yaml
  - ./magicauth-crds.yaml
  - ./nfs.yaml
  - ./synology-csi.yaml
  - ./minio.yaml
  - ./redis.yaml
