apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: arc
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.9.2
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: core
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
