apiVersion: v1
kind: Secret
metadata:
    name: webtty-share
    namespace: apps
stringData:
    SHARE_SIGNING_SECRET: ENC[AES256_GCM,data:8mI99nL2AkEwgpWMKp2EUVrCC4wHMCarERr1kA4Hdtb4diYaMQQ/PyvmqKA=,iv:HTiEQWq+6UXlj33b+GElLiXDqFI1QRGNbbQLqIbUBgI=,tag:5EW/9ah6r1ZOfoabaQuvZQ==,type:str]
    WEBTTY_BASIC_AUTH: ENC[AES256_GCM,data:TKBCVPIPOyHOocHIIhQn3TXqikgxh+yMZU0BqRI=,iv:nKn8LWv1KPjij0xFQ9eJfnDVLy4UmMeCaWo+Vg1Usgs=,tag:Xox5vfUOq3LtUEjWuOuf4A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:dGFHXaBZghvPP1dK0j3hlGAtoZvS4DZk70BrZeXskRww6c9NMIalJ1Qqd1ZW5AN7eilrsj9snxAhpRrxzlSGjCelHRxGDY38XwM2RgRAF92szHPd2WqT1ibZR+70nTgMXVjwF3rne2RtC1JmVO7J2lm4fK+3ByuVhMk=,iv:iVYWq3EK1tKgS4tvEGfRgtdAzon/bIJqUcyw8QU6SoI=,tag:ftaHmasaFTdqxUmaiLcblg==,type:str]
    WEBTTY_FILES_SFTP_PRIVATE_KEY: ENC[AES256_GCM,data:mA69Y4GfsNn2aw5QyWOJNWPBb8+N4MwnJaHH9SFzd5C8hCnXxWubl4silUWfeq80nHRWuUbTJJzzBD8QvFWb7LxPbZt6Q5QICSOozeUsQDM62WjsWJ754VLdkv6iHFeZB5ngtkAodg8wOhGitjsAQYEhlLeeRonh+idv1eAeM5wNvYVRipqRZNEPjfE/e4M4WZuUR0tZWurdUAKVkoZ5N0DNRZ+ZPfa2ijdeO+wjghhydBIHHL430fIQ4k5wuG6VrsTdQW9yVqlX65JbbVVt4Ljg5JOJAvAnUHHmX4MQaCyMYQYHlbNW2maPnklXaKd6zN9kNQua+nTViqhabvBU3c4AeXPo6LYPr4GDo9SeAx9CpPT+cHCI8MiWCRiXb3bmfQJnoUYp4p/1QsGxgS2QVdUkO5/LKkAua5khO1bjWyitNOv3DPFrv8cR7oJgT9ptx9ZvKCIjnrfbDV7fO90ydIfi6HkrdTqjyO0urtiNG7Rp6PQgTr4/k5iamcXdXIJALEwQNWyth+z04fudHvo7i/Ozx4n8uaZY/DsTTk0qUtGTfuPeIafXzR4K+1TacFZimtx3fADWIJgD9pUjG3JdGgEHjsvlZSA09X9UqGh+SbRAbeuArcLFCdmfxtC6RMzfglDbtWyiv0rLpvQZjQcmttGeIwqpNv5yv0n74wp6NIzXK3cjkAFLkULcskB4H3SUtMVCAGTsn2oTtWfgFYIMIJkIIQY=,iv:AKnr304kI8FbRd5dKZBwMbQ1m2MJZfGhzqVBBY4sqgA=,tag:Gbbov4XaU6RnBDJQ9VAWNA==,type:str]
sops:
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-31T11:11:47Z"
    mac: ENC[AES256_GCM,data:UI6Pu8QJnrwmckQ7TsMcscvAgvckel6Ywz/AGpidE9lZ15QNPX7rfZMMwzhkPlMaJopyHn7FlQ3bDUwq8G1jhevxOD24B6r8TmawmggXqjXqafdWT45d5On74sCsNnIw+xZ3Re16t0YIXHVOOy0e3iK1hkCNooYP1loTC5j2Af4=,iv:ZvJtKrAhnRUkhummM8hn20MvW3UzIhSDFwNl22dtm4A=,tag:pPa5bTLipNvSV9Ve27jr4A==,type:str]
    pgp:
        - created_at: "2026-07-31T11:11:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBARAAlnWPV03GTZ5PbxS/LvQx3lxwrVkYPPcM/vUufxlTWK9z
            8wkYZVqz7SBjxsWglPox6RaBi7xZFIcDjCfH40tjXID6w5bsChA9/HcE8B0EyPtv
            bis59ol8fyE2YZeQ+aTS4N1pUD/6P1/UoUoQ/pImpGb4MglUTrbFohwlVNyRGSXC
            /AC7UBod62dPsJN1lCi5Pmn+CyHMA/42fz4bcpZr6DsnaULVICukdBm8dSTkNs+M
            i0R5OD80k4ZduKukJkR6NhRyxTJdDE23LnNhD83OcQ7cTL/eQDWxUetPJJfLKCGd
            MBApwW43GPODdooslieHP9QYPSg1ZQFlhy9AYA5PVt86Ti6qVfo0X+h6g2ALh2cU
            m1+T1bLU2wGcHhcEEMKx5nTz2rOpO1m0H5OqEaBWgO3kaZbNBqft1tB1y+ERbsXG
            naQxobJFiPqgyEAmymHboUUdduUwM5ICnxUENR2si34E+x3ooFBRwCeyUVITJTda
            Zl7VRkcmlvgqNhSDvS8pFV4jOZ2VnNWaVK3ZnF67QK7kP1M51e+EjRE012PZKdor
            Zhho+SXeHqCG7AXZ+rrTW1i7BmKbJeUwEen6gRX6G419NXrDgcoUPrV+BTsmxdgt
            aJFu4S6i0+a98YXTzsSAR3ztv1GY6fcu/A6+e4OyZ0jIyBolAsWkrQ6gb5/g3D/S
            XAGRxB3PshpxliqwkMt+nGUMDeUHLkUYITxMMQMr6FY1QwCYJC1Kf3bXiuctMM4Y
            XoLs6XYwceT7CzOR0KmH4gkfXaxPORW6j2aa8bBI7MZb7XfDJkr1Du9tWCkk
            =GMpS
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    version: 3.13.3
