apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.15.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: core
  values:
    runtimeClassName: nvidia
    gfd:
      enabled: true
