apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vellum
    namespace: apps
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:5BuvwIStFtTxDsvpg0RVVY2Jy/JBm1wW+u/iORZDYGyjijPZPDg4/urF/LvJ7VfWMYCMc3Yg/AwZ6qTYcXP7G42fWBQAGV6RRA==,iv:o103NuK28muq39W5/SJAx88dvjQBMZxidDv0aVo7WS4=,tag:LM8HGSn3wMdcWnXZb56dcw==,type:str]
sops:
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-12T16:09:49Z"
    mac: ENC[AES256_GCM,data:VqXh5GPRFlrLTZxgfVBCZ2Fcqt2tTlUGZeEDTywsw39OEyo+44iA3btkqrZfwBAt6GkzwqTFoMg44q/jYdYd4zsJf27CJi3QZRvNiEj1TpXrmLvfg+iQ7yU8i0t9CgYfuCoPWmzUHdgz7WLl4iwuZGOToBipmK7KHEyD3JKU5AQ=,iv:ojTCC0pyNRfwfAtlHUaLVPoE4ra3H+RlGh+yNVYgXCI=,tag:+vVZAMn/v/NqN8BPhgb4Gw==,type:str]
    pgp:
        - created_at: "2026-07-12T16:09:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ//SdXH6gJ1sLLZqV9Lzih1G0lhKAq68EAiO/rCu85MvE4x
            2ItobTMVnGNYIDj/jwyOhiKZzAWy3QcFlQRUOPv2yJajSrdUqj8bnwPOX6czjgR2
            O1Z2SnpQB+dDFOYXtSlLMDrvtrSIQIOWmKgfcahljsySW01oAIvAxWIbI3GgSsot
            KF6mlDAfa5S6/LoSkUE7z30xcNWDmTq2p4KVvQzKq6rfXCTBckIaHgu1N5QdxCaR
            k1tNNvmBMR9z5zELoQTW/pN/SsZSUpHr5iC4wMYsxedC/earNbzhci3cLrIiClOf
            Du6dc5sqVhmHNgwqElcbQbjGOAPt/vHuiSMt2lrDZ5aemGryquyvREva3kkdo1DH
            9PkcJnc1nh6AiT7ALnh/BYgwvx2/QcMr5zMWIX/dwIHNzsgUBJBRVlSopnJSvqCm
            NKyh4lu6w7ZFVv14r7hD03XPC4IVm4tQhMo+QSxB8pC8Ffjpw3vcWsQ8WPvsydFa
            IDA1F/detrsJ0+ivVUmSW7dGQvmJ+hg7428WGLM8zPTRbjpuy1Mzg3zMnG7r3r82
            OCzFwEaRKtfTXUrddIZufF5/V8JJPjdEzACyzSZluTbELn/TUadymtPIUHIjANod
            QTwwRil3H9MGi8qv0uYW/zcKfsssubhABWOtloa/7D8HJuntmARjnstEU12TNdrS
            XgGl4HuTcC0bMcIOLCY5kl2omdPnw7x10//avTv3fkl2qR37SNrynTGCeNZLiCRH
            RaUnXak/y44Jav6M6V8qPM7Nvu2s58r1N+3ijqa86WvFHGLMp9FjubpS/iairZk=
            =bulz
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    version: 3.13.2
