apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vellum
    namespace: apps
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:5CunMvgCygWhvHEbNdytOBpAroAEGOuezBl2VLZ0r/NR2ch6xwyIwJ1kQ8+cb/n9jb/+j9qcxbY8EiwzL7jHOguWRc6jQp+HAw==,iv:m6UOJoB4xOfrPK8MRXpTn8Ww8sgZfgdAgus3pI+mS5Q=,tag:DhBXX0ffcDENSUHwbBhzXg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:TlNYG7JKaEDPnq5V2fKhuYhGd+BPhEhdnVKSx17AEk7afTtL546HN1JyFsBPOeir6vglx/9yYbNuryGzJDJXYlLxOXh1g21Ae0W+1Nnip1Du/+tzbFdMIcfwXN/ihpt+mFbjC9QLe4CfaHY=,iv:CS0t2aKEoeWPOWDiGZvOXSLxSZL3QRn8zUgwBQoVe24=,tag:H4T5NxwAUA6ElUBjQvPslQ==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:FzQ8BqGR7+Do3kxxZM7YdA4P4js=,iv:qGmWsUXB9fzvTcHZTwQabztFQYl/bwtuBNKV7bP1vrg=,tag:xGlvZc/jXhTrzQeSpSExmg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TdhIYVfD2GedJ83l/y7rzC5b98v++2ykN0uhINLx0hdKm2N+fhb1Rg==,iv:3PxqLb1TV+5rdbrg4xcDC7bfS5d7D+2LArgwU2MSu5c=,tag:3+JC5X3vvZL1BkYpK1zB8w==,type:str]
sops:
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-14T09:03:07Z"
    mac: ENC[AES256_GCM,data:E36rkFGoX/RI66RbFGUVl7osE4L3pVzdXdITfcuG3bPC2tJhqmBjGrl7mPwgcTIh4th2ESqF+KjqP3Krf4dxSKk/xFPxwfoTr/ivGw3Ha/CprtyJ/WVShbpgt2Od0d/ThOyp65Py4g0BPygNkO/KIpQnqcNEAdjXecyo1aLmbqU=,iv:kifaIzFSomCmAs2GFqrz46sBcrUgFsUcYYb3QbAi778=,tag:BvD2YoVtqKmGTdHSCGviug==,type:str]
    pgp:
        - created_at: "2026-07-12T16:40:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ//boGL149eDYN19I27JHatxIgGzIaovOev4ipmbizRetKS
            O26yXVNkOKUgkNhdlBmJVxUut12OAc74wsj0qDBVLR7wiLyi3J3abQPyBLpZIwgl
            LSHiJi6P1DM7V+BXhaVqqcv1c9neJNNH9SNhLltpwcS/2ikrj6wEacF38RGlyZXy
            H8PKmBXIcRlkKhopydcXz2gterqj8t0hCUIu4fTMiNm0mL3drmTqB96n3snv1iXG
            BuInaA+NWJD22CgyrJR4exfAYH1h6WtzwsDI/HKTMFORnC1BrV9O0gVX/Jf/N0TK
            f9y8bdqb3s1R3PP+CHQ3HuwTE/SMCcIVNSTjeNDZsAfe5bwWuknY5SdZTg95u5AJ
            bByLRyTpOW5RivRgXhj4hGChW+/Ol6+98j8Iyq0X0Y+PmnB3ZsXqb6QBDP9EVTey
            HL4kNSGhQ7Oab4qqWMfFRs39tHok47leVT0SNcMXhob82CtyylqQQv95C28yXD/M
            8N+nYwKB6srDnYMY6mvShV7gxvJ07ZWcCsA5ChZRV1fnGAN/ddFY0jaK2uXM2l9O
            3uALOYeL+ODAdGWGUIRcHIZaE3q7K/Mxyr768tn7SGaqTNnn87vWMfbUvRz1BUlU
            dLRedc8rXjQ2XdQy7Jrb7tYeZVRwOtr2HmzVx+sfPkq0HZQ7avlKBHW8Xu00ndPS
            XgHaVd4F33OZjLUoLzTFSov0fOGpKvKMt/0ydMbC8QnqqN0Kw/7PsnF8MbZe++23
            m0exdYKTtiFKycfV3EXvhaot+++ToPyE0RtcApRR2bv7w0mySBehjKl/b7RiHAU=
            =HRKB
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    version: 3.13.2
