---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: union
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: union
        namespace: core
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: union-values
