apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./ingress.yaml
configMapGenerator:
  - name: union-values
    namespace: apps
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
