# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.3.0/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: roundcube/roundcubemail
          tag: 1.6.11-apache-nonroot@sha256:fcb4cd1f6111160596ca5433ea8178645b886fecabeb30d900aeebb4d7bde0c2
        env:
          ROUNDCUBEMAIL_DB_TYPE: pgsql
          ROUNDCUBEMAIL_DB_HOST: &db-host postgres.core.svc.cluster.local
          ROUNDCUBEMAIL_DB_PORT: "5432"
          ROUNDCUBEMAIL_DB_USER: &db-user postgres
          ROUNDCUBEMAIL_DB_PASSWORD: ${POSTGRES_PASSWORD}
          ROUNDCUBEMAIL_DB_NAME: &db-name roundcube
        envFrom:
          - secretRef:
              name: roundcube
    initContainers:
      01-init-db:
        image:
          repository: ghcr.io/onedr0p/postgres-init
          tag: 16.1@sha256:dda75857689116d9c233ec0978cb905da0f952618dfbe1b8731aa1071044eaf0
        env:
          - name: INIT_POSTGRES_HOST
            value: *db-host
          - name: INIT_POSTGRES_SUPER_USER
            value: *db-user
          - name: INIT_POSTGRES_SUPER_PASS
            value: ${POSTGRES_PASSWORD}
          - name: INIT_POSTGRES_USER
            value: *db-user
          - name: INIT_POSTGRES_PASS
            value: ${POSTGRES_PASSWORD}
          - name: INIT_POSTGRES_DBNAME
            value: *db-name
      02-install-identity-switcher:
        image:
          repository: busybox
          tag: latest@sha256:2f590fc602ce325cbff2ccfc39499014d039546dc400ef8bbf5c6ffb860632e7
        command:
          - "/bin/sh"
          - -c
        args:
          - |
            cd /var/www/html/plugins
            export IDENTITY_SWITCH_VERSION=2.0.8
            busybox wget -qO- "https://github.com/toteph42/identity_switch/archive/refs/tags/$${IDENTITY_SWITCH_VERSION}.zip" | busybox unzip -d . -
            mv "identity_switch-$${IDENTITY_SWITCH_VERSION}" identity_switch
            mv identity_switch/config.inc.php.dist identity_switch/config.inc.php
            cp /config/* /var/roundcube/config/
            chown -R www-data:www-data identity_switch/

defaultPodOptions:
  annotations:
    reloader.stakater.com/auto: "true"

service:
  main:
    controller: main
    ports:
      http:
        port: 8000

persistence:
  plugins:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /var/www/html/plugins

  extraconfig:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /var/roundcube/config
  tmp:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /tmp/roundcube-temp

  config:
    enabled: true
    type: configMap
    name: roundcube-config

ingress:
  main:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/hostname: mail
    hosts:
      - host: mail.${TAILSCALE_DOMAIN}
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - mail.${TAILSCALE_DOMAIN}
