apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: metallb
      version: "0.15.2"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: core
