apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: hypnos.qilin-qilin.ts.net
  name: hypnos-ts
  namespace: core
spec:
  externalName: placeholder
  type: ExternalName
