apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app windmill
  namespace: apps
spec:
  interval: 10m0s
  timeout: 1h0s
  chart:
    spec:
      chart: windmill
      version: 4.0.51
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: windmill
        namespace: core

  values:
    windmill:
      image: ghcr.io/windmill-labs/windmill-full
      tag: 1.614.0
      baseDomain: &windmill-domain wmill.${TAILSCALE_DOMAIN}
      databaseUrl: postgres://postgres:${POSTGRES_PASSWORD}@postgres.core.svc.cluster.local/windmill?sslmode=disable
      npmConfigRegistry: http://verdaccio-npm.apps.svc.cluster.local:4873/
      appReplicas: 1
      lspReplicas: 1
      workerGroups:
        - name: "default"
          controller: StatefulSet
          replicas: 3
          extraEnv:
            - name: INIT_SCRIPT
              value: "apt update -y && apt install -y expect"
          volumeClaimTemplates:
            - metadata:
                name: windmill-workers-default
              spec:
                accessModes:
                  - "ReadWriteOnce"
                storageClassName: "nfs-client"
                resources:
                  requests:
                    storage: 1Gi
          volumeMounts:
            - name: windmill-workers-default
              mountPath: /tmp/windmill/cache
        - name: "native"
          controller: StatefulSet
          replicas: 1
        - name: "reports"
          controller: StatefulSet
          replicas: 1
          extraEnv:
            - name: INIT_SCRIPT
              value: "apt update -y && apt install -y build-essential chromium"
        - name: "video"
          controller: StatefulSet
          replicas: 1
          extraEnv:
            - name: INIT_SCRIPT
              value: "apt update -y && apt install -y ffmpeg"
            - name: WORKER_TAGS
              value: video
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp/windmill
          volumes:
            - name: tmp-dir
              emptyDir: {}
          nodeSelector:
            kubernetes.io/hostname: hydra
        - name: "libreoffice"
          controller: StatefulSet
          replicas: 1
          extraEnv:
            - name: INIT_SCRIPT
              value: "apt update -y && apt install -y libreoffice"
            - name: WORKER_TAGS
              value: libreoffice

    postgresql:
      enabled: false

    minio:
      enabled: false

    ingress:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/hostname: wmill
        tailscale.com/funnel: "true"
      tls:
        - hosts:
            - *windmill-domain

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: windmill-app
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: windmill-app
              spec:
                template:
                  spec:
                    initContainers:
                      - name: init-db
                        image: ghcr.io/onedr0p/postgres-init:16.1@sha256:dda75857689116d9c233ec0978cb905da0f952618dfbe1b8731aa1071044eaf0
                        env:
                          - name: INIT_POSTGRES_HOST
                            value: postgres.core.svc.cluster.local
                          - name: INIT_POSTGRES_SUPER_USER
                            value: postgres
                          - name: INIT_POSTGRES_SUPER_PASS
                            value: ${POSTGRES_PASSWORD}
                          - name: INIT_POSTGRES_USER
                            value: postgres
                          - name: INIT_POSTGRES_PASS
                            value: ${POSTGRES_PASSWORD}
                          - name: INIT_POSTGRES_DBNAME
                            value: windmill
