kind: Secret
type: Opaque
apiVersion: v1
metadata:
    name: outline
    namespace: apps
stringData:
    URL: ENC[AES256_GCM,data:8KpCjGIBxLgYrOA0Gdluy2t9MzJst+nu27keB30y+vRvCYM=,iv:bsRB+WLwHIBHzfI5rJN0QyIy5dTgDGjnEAKOTMGg1Ys=,tag:13RGbKAnmsY1z/lEONUToQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:V7GaSEy4YIpnmUdOBe+Pp3a11BG/1R25nWcbcguQe2DaU+PVpJYCnqAcJy1v16vXW3A5gtWhLpiXb/7iOYbu7g==,iv:bzzLznZc+9YcVBc2zJRoQ3nV4ItRK72G7s+FEpQo3MY=,tag:+3RKfwkpD9tUaFukISWMLg==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:xiwYtV06c7Rfxxr/uyK2UmrVqBExrGUbv9QQZpZUj2OC6kdpeNDN6K8AtvZDxD0tlS5KGKonUvRyDJaffYm+7A==,iv:LnWN5udQI667JaDaUBcvcA6OnATmHj9eleybM0yTaL4=,tag:2peTDD37NrXRUlRHA5u3OQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:OgM/x2uZFhbasPnm1DLxe7PDLBo89W4WFsjRg2p+kJpzuCQ+9nzIIvmCkJfOunXWivLIrPBcNrUOetEEPJPHnhrC8ipx5BB+LTMvvs3RRVjJMlVucw==,iv:N5O4q1/m4XkZ7Hv8s3CtfAbVq8GGs/ndJ2Q+MByPlc4=,tag:zO1Q1ktvlpkNonkTMRmG+Q==,type:str]
    PGSSLMODE: ENC[AES256_GCM,data:yCK62ckVEg==,iv:dReHkWf3XT1mYVU+yTXSCHfflXpcxCizrsULp661sKw=,tag:oMve0TnI0RtPUSS7gTUeJw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:03yV84abG+AM3p5SXJGTZYDjmer+czN+Us+Qa+1Izis1PYfiwAbZZi2uBw==,iv:T7uk5kFX2zFqWYsorueR1IudCumj8ZsHa4uJqZiBfd8=,tag:jAtcZf4teNrP7tRrEwI7rw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:///Y0+N9HLImNvjYXRn7Lw==,iv:uBbE6DicxxD2chFCjusS5I1Aup/+F3oHgaNpMWHNOoE=,tag:mUUnVkGtSYRrRWtlyaA2yg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wd7QHGNbu+vtPxCbaSQCNLO9qxNv4oaTK5gtQhP3q80=,iv:BrASOah8PrdVk2F8xauUuGQSKK8wTWBRcXmlRYiPoCA=,tag:q78y4buD7C0CsPnqvq3Ypg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:GZl+FQOioS6A,iv:eEGN+UH5NkVf19QMLHjCOiK4JNEDp8lWq27eiMHeMd0=,tag:mwFNocbzQQ9dDcex5qSwWw==,type:str]
    AWS_S3_UPLOAD_BUCKET_URL: ENC[AES256_GCM,data:fLKsBDkC9DuIrsd4sJJ5E5X2CeeeR8+bxI4YS1y3uRBj,iv:VC7hvzkdlU5PZzVORFDQDxJMqlh11EIy/l8R2FibAbc=,tag:GaWrXYhap/bxrn1xnqAdQw==,type:str]
    AWS_S3_UPLOAD_BUCKET_NAME: ENC[AES256_GCM,data:L6kfhBC2hw==,iv:GjgG5tTgQUjlefrxIYEB8UrED11HZOFTeW/6/ZG733Y=,tag:bsYsfck4cx3gfg6tkPRAPA==,type:str]
    AWS_S3_UPLOAD_MAX_SIZE: ENC[AES256_GCM,data:4ZwS68Q/1Og=,iv:U6UhEsPu9QlwFQC7PCbWhRHFdHgBIaRrXYgffYXmyyg=,tag:5t8JMNftLjTlzhS7mZQ4Qw==,type:str]
    AWS_S3_FORCE_PATH_STYLE: ENC[AES256_GCM,data:ygxFfg==,iv:26M4Ao7BVb0J2TDYqC3Y+GizmD2w+5WY1i2dTrIsDYo=,tag:9g/Oo7UfN9Eq/9cH4DSbLQ==,type:str]
    AWS_S3_ACL: ENC[AES256_GCM,data:Ft8sWsnfIA==,iv:km9yB9Abpe8vDz0UTQ7cTGg6aGojA9L0wGrW66KewMo=,tag:saGVTNt03m8eZ4kvkB2C2Q==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:S3SKN9Ax3g==,iv:wDcYoauDop5KzfdQNP1Y3fS3MN8WWtlwCTQRovDignA=,tag:pN5Zp4lH4oQWMy9/fnAa+A==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:+I+SA91VkefMGMY9saa+2n7HotGS6g==,iv:oNry3d9HokJAu2NZ2BSXcX2hFG2pTYTjnUjExpX0mqw=,tag:c1ZwlY+kvfRUwKJJZsSCnQ==,type:str]
    OIDC_AUTH_URI: ENC[AES256_GCM,data:bagHnrmPQmURcIWxgy5evELpny0MAxR7uVO4vAlsZnrsdZIHPg==,iv:QspwFlFMzqblg2ib3GvBXSoYO40GplqXtm7wLyb7hBM=,tag:vAETxrlgWynADL8PD6mPdA==,type:str]
    OIDC_TOKEN_URI: ENC[AES256_GCM,data:aI/N2SOYB1i7EsSIZ43cYpNNHe6VrVnkoIhJN/12dbo7qXLeMJs=,iv:GooQcUjcoaQ6D9Wkc/PQX065BZhaljg1v14hsjxjnBM=,tag:mdSP9BFXPKeMzpt6FTtpEQ==,type:str]
    OIDC_USERINFO_URI: ENC[AES256_GCM,data:77OvHRVB1YjwjKTYg97dkGMXq1v5oMZhTZn5xm4bDtRCHyAEILAmU9U=,iv:0EoWqCFFJddBqkMxskykIQMXx/Vz7zSFvVpd0BwvSzI=,tag:qGNWqSgLI/jAWsjhjk01MA==,type:str]
    OIDC_USERNAME_CLAIM: ENC[AES256_GCM,data:iLuG,iv:7TB7SqmVKvV/e24+4cLdj9afuupjfQngpiLklRvk8aY=,tag:QL0FW2gLnp9BoOb76j6CKA==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:F8L75JrM,iv:2TXMOQYdGeW6LGHPEMtCXGjynHo5RCO88sBhEHVwHKY=,tag:nMR7YMW6lfBK7CZ1SZSsnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-27T21:13:28Z"
    mac: ENC[AES256_GCM,data:uPx9k1LOi+TWVqUDJZ1gMA3wzJhD/JhZep6zOMXmRW3V1ESHVRbsuoksboSbT2NlpOFARzHoxzNM5E31ernaK2VWJSwP4H0fHG04rmXE3aQp5UFW2ImwOjwJCmLOQjievT8CJ9PrIq/3qBWrhTKaLCAtON5VeXPP0oWKU20t4p8=,iv:QUoeHtrf9/N7hr5csZLuQsvF4homPR7eOuegmxDHfe4=,tag:ktqn0Odh2C7ksYHUuMpwpQ==,type:str]
    pgp:
        - created_at: "2024-05-27T20:51:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ//ZP3sA2wQVA0XojdxG7l8GZC6dbmmZqgTzLCShe5FatA8
            6o+5NcT3kNDe0XdkEBLnsLZHBFj3qJAVTBuEuj6iY7Mf9ENvVGRpuOO2lGat1Hwu
            XRDgkzlp3u4UHomP7ttodOM+/mKBfewRRxYI6XoF49ebLK3SgNrXo8z8GxMrmS1x
            PXoN908eMwjnXZgq0pKCKbsm32Y2J1Py2WD6dK8ZjntMC5XDMfHkvMQ4x6Mom/iP
            2K5p2r/UvQxbhTJGiOEpTB0GQymd49tmLtHVz8UHmUQQNxN3qV3E5Tkudcv/7ZZC
            MJv1vfQq1/h7XSkWI9kSS232EBHXG/cA9YyyF+b9xbFvs9rpbMe/I1dqvxGWyBJ5
            CfCAPmzpKikzPMxiHF3StOfoiaJclGOxiQ5MHNIR6BP54TP2b8HKzm0cmiWOcIJl
            2foFwHJE+I4tK2NCNd8EoUwzknYf4bTpdzMPhQusiAdzWvyJ4LDnOxs9x6xMzilh
            kbDxlPww6Q82A8mEfE3omweKtVqSldqGcDsH0OZErYqN18qX9w9cQhNyqrWwqL8o
            TVmETOMJrhKMVZ9Yo7wwQ2Nh5FYh39UGTSGXaamH045o+RqzJysDr8si3nXAgVFP
            KZjfEGb4H1PJj0y5kA1F92nf5FP1M+HUX2zUna+sdCw2l1Bu78Zjo3x1wHHOXNrS
            XgHQVRlEjDWsrREwdcxPbWT2hFuCMagBKT87hza1SvggEvnPWvkhB7ydxNwRXUet
            M5T1c1qMf0vBbg8NyK2Cv4BUuoxnDqOBErUjTgJHBO3nT2EPGt0/gnhuwZUEOeA=
            =sr3S
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
