---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: core
  install:
    timeout: 30m
    remediation:
      retries: 3
  upgrade:
    timeout: 30m
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/qbittorrent
              tag: 5.1.4
            env:
              TZ: ${TIMEZONE}
              PUID: ${SQUASH_UID}
              PGID: ${SQUASH_UID}
              WEBUI_PORT: &port 8080
              TORRENTING_PORT: &bt-port 50413

    service:
      main:
        ports:
          http:
            port: *port
      bittorrent:
        controller: main
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${QBITTORRENT_IP}"
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          bittorrent:
            port: *bt-port

    ingress:
      main:
        enabled: true
        className: tailscale
        annotations:
          tailscale.com/hostname: "qbit"
        hosts:
          - host: &host qbit.${TAILSCALE_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: qbittorrent-data
        globalMounts:
          - path: /config/qBittorrent

      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config/.cache

      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/torrents
        globalMounts:
          - path: /mnt/torrents

    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: "true"
      nodeSelector:
        metallb-l2: "true"
      dnsConfig:
        options:
          - name: ndots
            value: "1"
