---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: core
  install:
    timeout: 30m
    remediation:
      retries: 3
  upgrade:
    timeout: 30m
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.4@sha256:9d9c2384f94b12831c5650afc8d25f313ecb09cfd8cb434dda6da9fb39cbccfe
            env:
              TZ: ${TIMEZONE}
              UMASK: "022"
              QBITTORRENT__PORT: &port 8080
              QBITTORRENT__BT_PORT: &bt-port 50413
        initContainers:
          01-copy-config:
            image:
              repository: busybox
              tag: 1.36.1@sha256:6d9ac9237a84afe1516540f40a0fafdc86859b2141954b4d643af7066d598b74
            command:
              - "/bin/sh"
              - -c
            args:
              - cp /configfiles/* /config/qBittorrent/

    service:
      main:
        ports:
          http:
            port: *port
      bittorrent:
        controller: main
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${QBITTORRENT_IP}"
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          bittorrent:
            port: *bt-port

    ingress:
      main:
        enabled: true
        className: tailscale
        annotations:
          tailscale.com/hostname: "qbit"
        hosts:
          - host: &host qbit.${TAILSCALE_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: qbittorrent-data
        globalMounts:
          - path: /config/qBittorrent

      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config/.cache

      media:
        enabled: true
        type: hostPath
        hostPath: /mnt/torrents
        globalMounts:
          - path: /mnt/torrents

      incomplete:
        enabled: true
        type: hostPath
        hostPath: /mnt/media/incomplete
        globalMounts:
          - path: /mnt/incomplete

      configfiles:
        enabled: true
        type: configMap
        name: qbittorrent-config

    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: "true"
      nodeSelector:
        kubernetes.io/hostname: styx
      securityContext:
        runAsUser: ${SQUASH_UID}
        runAsGroup: ${SQUASH_UID}
        fsGroup: ${SQUASH_UID}
      dnsConfig:
        options:
          - name: ndots
            value: "1"
