apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: synology-csi-retain
