# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.3.0/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/autobrr/qui
          tag: v1.14.0@sha256:7455e0b2d6d09b5a638d55eb43c4a7a9add16ad5162c2c071b664a8a8a726a4f
        envFrom:
          - secretRef:
              name: qui

defaultPodOptions:
  annotations:
    reloader.stakater.com/auto: "true"

service:
  main:
    controller: main
    ports:
      http:
        port: 7476

persistence:
  config:
    enabled: true
    existingClaim: qui-data
    globalMounts:
      - path: /config

ingress:
  main:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/funnel: "true"
      tailscale.com/hostname: qui
    hosts:
      - host: qui.${TAILSCALE_DOMAIN}
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - qui.${TAILSCALE_DOMAIN}
