apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: image-host
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://github.com/invakid404/image-host
  ref:
    branch: wmill
  secretRef:
    name: flux-system
