apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: image-host
    namespace: apps
stringData:
    WMILL_URL: ENC[AES256_GCM,data:HAb68Sw+VU8avLK3sOnMqwYzN24TfVZZhnGkMqJ3HYLQKOrilk20klhCeMEotO4=,iv:dE18ILwnhd9FuDE6s7oEgOiP1uNST2uqLNu0io66eqM=,tag:xBtu5GrH+l6TfUEC/kWO7A==,type:str]
    WMILL_TOKEN: ENC[AES256_GCM,data:8BQSyay+0x5yKwdOsft65l7ggQQOjlGoIK6xv9WYO2o=,iv:oCloE8ajuMIdM8loPsJq6XGyxncxD7WQJTjRFYGkSXA=,tag:pbwyVS7gL2EwI8Kd8BwfGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-20T10:50:02Z"
    mac: ENC[AES256_GCM,data:iqdNxgMnwiXikMTTIK2xLafXgw5hedzHs0IPfZnMp2PKc30ECGc0PlS4Cn91vrYhXBn3BMKhU13REnBBEeDPra0UlJmxEGZW226dnNIcBNcM2lrjerSnQQg8tOV5KoNmlgTIXOPkO+iVwEaa/ovUJqSk8BEhmvn/lxI+hJp4SI4=,iv:IUIUi2niMvrWBm5U9H1/H555mdu68ff1UIwyY+yEEio=,tag:ZVTC2j+k9mohb+fUiOqhwg==,type:str]
    pgp:
        - created_at: "2024-04-24T10:29:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ/+PHdQ2tE5xYZ8fxXew30+Xw7/B/hcCJ2iEtnk6yImIb42
            GxoTE5rseCF5sc6t0/iLTzen80xgBT6bNOXsfr8nI3KxtmlEfJr0t4b46zA3WAXn
            YnMhPTRPbQmdjBaYIDUUNFejtzQ1f2hsA9kDYSuO6cA0u++y3Gy4BrlZ4hOWwF38
            5uEXxa/z+L0erl6fkiR0b36ESz+MClrPkI/2L7udRvbI2qMX40EV9okYg7tGvhC0
            nkQBq/9iLyVLr8OJUE0UZCmfvBiPd86CAlYHs0LxpPAY6o32ISoktT4olgIvLfAO
            jxBZjrwL5RGhOMpAyskl7mSrprm1IXWgXcyPpJZv3b9ePAzc42/kbwjnF/LrypN3
            A5zxIcPUt2f0sGlxeS8748LPqwt6GIk8IIog04+fN8mvqegz10GzaI6bJhmL6qeB
            aUCZnYHAOrMV+kCnR49OxP0w92p32D8K+AqZGjkwNJhx0svZMF+A77bfurTVSOf3
            L3bv572C6E0EQWdO+OghYeKEBvfeuK5LnDucJFvbj/3l0XqJva07YbUxR6Anw9ER
            ZNZoLIoVg+n12Jg8E81qvR/uwHVBHzsj6VAMbjT5WcMCBnSRU8s6ImP4pjctDXle
            xiAMBkUyDSNhNLVpoPVuZ1sTvr1W2cf+fHgzYNRH3hfgROntBdNQmcoBnBQDp63S
            XgHDTCBzV90YLRu0o/NtNdQIfuv3zlwXLNZpcipQ2IcJBn2Q/rOsrcYZhHtNeEUr
            saHnFhw7cJR0woJcwbQ8Uc+6BYbffL680BSXPzNrtr9i/5WDZG/lLNncVwO4shg=
            =AiDA
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.0
