# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.1.0/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/invakid404/image-host
          tag: 1.2.6@sha256:56031885f1497c5c9961d9fbe4d43b7044b096d8951537c76fccf805a2bacb62
        envFrom:
          - secretRef:
              name: image-host
    initContainers:
      01-init-db:
        image:
          repository: ghcr.io/onedr0p/postgres-init
          tag: 16.1@sha256:dda75857689116d9c233ec0978cb905da0f952618dfbe1b8731aa1071044eaf0
        env:
          - name: INIT_POSTGRES_HOST
            value: postgres.core.svc.cluster.local
          - name: INIT_POSTGRES_SUPER_USER
            value: postgres
          - name: INIT_POSTGRES_SUPER_PASS
            value: ${POSTGRES_PASSWORD}
          - name: INIT_POSTGRES_USER
            value: postgres
          - name: INIT_POSTGRES_PASS
            value: ${POSTGRES_PASSWORD}
          - name: INIT_POSTGRES_DBNAME
            value: image-host

defaultPodOptions:
  imagePullSecrets:
    - name: docker-config

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/funnel: "true"
      tailscale.com/hostname: img
    hosts:
      - host: img.${TAILSCALE_DOMAIN}
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - img.${TAILSCALE_DOMAIN}
