# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.1.0/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: caddy
          tag: 2.8.4@sha256:60c984f83bb0a3c2ac8f9dd067672dd6b8d6719baf1fe712fc52c7b221ce4e02
        envFrom:
          - secretRef:
              name: image-host

defaultPodOptions:
  annotations:
    reloader.stakater.com/auto: "true"

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

persistence:
  config:
    enabled: true
    type: configMap
    name: image-host-config
    globalMounts:
      - path: /etc/caddy

ingress:
  main:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/funnel: "true"
      tailscale.com/hostname: img
    hosts:
      - host: img.${TAILSCALE_DOMAIN}
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - img.${TAILSCALE_DOMAIN}
