apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: redis
      version: "18.6.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10

  values:
    architecture: standalone
    image:
      registry: docker.io
      repository: bitnamilegacy/redis
      tag: 7.2.5

    auth:
      enabled: false

    master:
      persistence:
        enabled: true
        existingClaim: redis-data
      nodeSelector:
        iscsi: "true"
