apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: magicauth-crds
  namespace: core
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: magicauth
    namespace: flux-system
  path: ./crds
  prune: true
