apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: magicauth
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-system
  url: https://github.com/invakid404/magicauth.git
