apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: pplx-tracker-values
    namespace: apps
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
