apiVersion: v1
kind: Secret
metadata:
    name: kratos
    namespace: apps
type: Opaque
stringData:
    DSN: ENC[AES256_GCM,data:wskcKn71JhII+suN3dOW76z/8hi9jcz5jlgMoR1pDVlRoxnfDyTl2XvfbFa03spAsqnTqilB+hCo0IuZpix+J1fynE3E+gpmsR62pfketvZI1j3x+GTBCNPy5I4RFxcSVlJz5XA1VHlk0IG/Mz6/ojkgf83NnKVoEIOIrHLu,iv:+Zo57LZddHwb38xqqvNug31SDHdVthd+DQzpH1TLCSI=,tag:shPSu+K+BUXLAAi6SqgSRg==,type:str]
    SECRETS_COOKIE: ENC[AES256_GCM,data:fuj2cdXLrIHPEGvvGMl4u29yI3UGrlUyQ7jR25t6kOw=,iv:G6K6nLVcM/QzwkAoVap5KAqTnh3ygcxKNrBY4xX0a3o=,tag:+MOKTjiFAbNC8OdVBt+X7w==,type:str]
    SECRETS_CIPHER: ENC[AES256_GCM,data:rtnw8U+dDV/Qa4Ubyg8B9XJdJXzGb26rgEEkIWL4VFk=,iv:GglO7btuLFisekkAiMmjY/IftiA4wjgkRhDgtJhxP2Q=,tag:csQCdE5xBXsJZi8006WTQg==,type:str]
sops:
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-13T20:15:19Z"
    mac: ENC[AES256_GCM,data:DiN6c8LYcCbz4LyMDlLXCGo05rT9qVvHDvz9ayiMJE8VfzvtyroWEa+tUD+NgflG80VLsCq0v2hFUufR6qETsx9+Z+95BJavkYpkeCn6aaM0TbgIcr7S3hJUeKUEQsGLSuhOfdjvSNL1MWgT2jqRYKnMoa0y3Mmw+gFasziTS28=,iv:Rdxb8E/ImuWzUPjsExtN3I3LP4VyxUao7z6ab6hFZ/k=,tag:UwzpkpK7KcC1sLi0IAWXMg==,type:str]
    pgp:
        - created_at: "2026-07-13T20:15:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBARAAhEv5aatIXe21nfc2xWfX6i5KgaO8pKdIre8h7gcyxbmp
            y/SgKjHsqJauceg/luI46UtccQFk92L36C1zZF1tCimQs4pvL/0w6iQGS0gG3pYr
            vLFLiG0OhVAgIhTUqmmqrz+MGH28A96O+mlBTcSgTq7TL+RzNU/G499XjoaQMTW+
            Nj0ZTqCTTXbycQHEgz2HEu+HVxzbKCXUArb/9wtiGgwBAJHf58I48JWDzUOrcbg3
            MFLBNqnz72JuuFVqiyjEinC3BVUThiR4FbZLv6IhN8hm8JZI/T9IkVMql4B0Sd0m
            rB0af3WoDkE0z2SJzdkTpzVOt1330THGOVs2sRW3QP+eLMPIwCflp8O0tpNUYnQB
            Mg+p1koY4RZQOmf5iCO2aVl/brVxnhI71sayEBTL26krPsypQEyKUuZe8PADB5FG
            Vm3lPKjiTJrqaFn5ePdqsqb79fevUgXvMZOabz65bPl6odcmcDk7pkckzHhz6RLO
            KUEQ/Zw+c+2vKvEmkVQqDXPIaRzsltbMTRDEjrhs3Fw2yz6GW/BWMSTHEka5BR9F
            0NiOvbNDHQc1Daj3OqRktWiSlo1eEtgZNqaGhnfHVKa5sVZSr58oKYwqwZHtu/ma
            jlYUSUpv447p7ni+nqJqsB7IoHChxNN3tTT4xNQkS3a+wfCGx/ASTYwEYBuE6WvS
            XAGY1vbDAMLVjjtpUsZsQRU+3c5R5aUtugC9c3EnxxJwmrM3TLG0GjpCD9Mt0rwK
            TSFnxdmSneBfHy9ebCQpiw9gLsS+R8pLEqNzWzl2rfJsoxX3Gocatleg1jw3
            =izYb
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    version: 3.13.2
