apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-host-config
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: image-host
  path: ./manifests
  prune: true
  wait: true
  postBuild:
    substitute:
      CONFIGMAP_NAME: image-host-config
      CONFIGMAP_NAMESPACE: apps
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: apps-base
