apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./arc-runners.yaml
  - ./arc.yaml
  - ./base.yaml
  - ./fagsts.yaml
  - ./filebrowser.yaml
  - ./flaresolverr.yaml
  - ./govee2mqtt.yaml
  - ./home-assistant.yaml
  - ./image-host-config.yaml
  - ./image-host.yaml
  - ./invapaste.yaml
  - ./magicauth.yaml
  - ./mergedoc.yaml
  - ./mermaid2svg.yaml
  - ./miniflux.yaml
  - ./mosquitto.yaml
  - ./open-webui.yaml
  - ./outline.yaml
  - ./plex.yaml
  - ./pplx-tracker.yaml
  - ./prowlarr.yaml
  - ./qbittorrent.yaml
  - ./qui.yaml
  - ./union.yaml
  - ./verdaccio.yaml
  - ./webhook.yaml
  - ./windmill.yaml
