apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: core
spec:
  type: oci
  interval: 10m0s
  url: oci://ghcr.io/actions/actions-runner-controller-charts
