apiVersion: v1
kind: ServiceAccount
metadata:
  name: magicauth
  namespace: apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: magicauth
  namespace: apps
rules:
  - apiGroups: ["magicauth.invak.id"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: magicauth
  namespace: apps
subjects:
  - kind: ServiceAccount
    name: magicauth
    namespace: apps
roleRef:
  kind: ClusterRole
  name: magicauth
  apiGroup: rbac.authorization.k8s.io
