---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.1.0/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/invakid404/magicauth
          tag: latest@sha256:8587709b40d13b398b2965f4b49f802b11cd20a959cbe528995a5b7e3f2a92b3
          pullPolicy: Always
        env:
          MAGICAUTH_PORT: &port 8080
          MAGICAUTH_BASE_URL: https://auth.${TAILSCALE_DOMAIN}
          MAGICAUTH_ENABLE_K8S: "true"

defaultPodOptions:
  imagePullSecrets:
    - name: docker-config

serviceAccount:
  name: magicauth

service:
  main:
    controller: main
    ports:
      http:
        port: *port

ingress:
  main:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/hostname: "auth"
      tailscale.com/funnel: "true"
    hosts:
      - host: &host auth.${TAILSCALE_DOMAIN}
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host
