---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.1.0/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/invakid404/magicauth
          tag: master@sha256:2ec30d4aca65f77199cde67d4eec1ee83c73764a9cd7de18451073526e7133eb
          pullPolicy: Always
        env:
          MAGICAUTH_PORT: &port 8080
          MAGICAUTH_BASE_URL: https://auth.${TAILSCALE_DOMAIN}
          MAGICAUTH_ENABLE_K8S: "true"
        envFrom:
          - secretRef:
              name: magicauth

defaultPodOptions:
  annotations:
    reloader.stakater.com/auto: "true"
  imagePullSecrets:
    - name: docker-config

serviceAccount:
  name: magicauth

service:
  main:
    controller: main
    ports:
      http:
        port: *port

ingress:
  main:
    enabled: true
    className: tailscale
    annotations:
      tailscale.com/hostname: "auth"
      tailscale.com/funnel: "true"
    hosts:
      - host: &host auth.${TAILSCALE_DOMAIN}
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host
