apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: lowrider-nav-google
    namespace: apps
stringData:
    api-key: ENC[AES256_GCM,data:ONsfwXzlDfXYdAlnUdky1ig9+Bt7lBhsbmP8qV1D2cyrPAOZgueW,iv:jABpXo+HJiyC6K8QNt6gY3iTrhVBu1KlEyAi8D213pM=,tag:3i7T3QvChIBFRN8SJq/n0Q==,type:str]
sops:
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-12T23:09:16Z"
    mac: ENC[AES256_GCM,data:4gJqVa+W8gJqLykZIwitxn7TTpHpEFWbEdOpW5W56EVbt3lq7UVCiPtIcecfsu/l05jVgfNAAsynyaTVxnEe91gvVOs7i32PushjmdhAJuCwdEoeJsjR2hajHr3QMZJ3DnrHYSp2Ipb5DOkx2ruRSKW23oX6mBX+Z2fJcmrt/pY=,iv:ksHfuEYOzrEgtmyDgR3SKCAXApa+wth8a+EOwlmHBPo=,tag:DlKXh81XDKS5fXoEd3VyOg==,type:str]
    pgp:
        - created_at: "2026-08-12T23:09:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ//cjIlT/ThhuoAcJEgvNC/UE+kicYBpxp9OcqtT83pfr4C
            Zh0OAZPjYjt8XMSwPEVBcy87pp3HgaAVNL6KHEYiLRE4+LKxsMskheIFq28K8WrK
            eyD7ag61zQdiL57JbS9z4PmWwGlEiRj9wy1vOKOvzopp/J6qDmr5pGB6Njf0+RQw
            0iy9RprmMLvzRhULfdUXGBiA1ISXcPPcr5j74VzTMOaf+wv2jlTzDbcMOvkc5yt0
            z4cBvRLnV1B6u7tkKRfcHBTkxWvG+sAia44RMdS/un3Cc9IXN2UOhkRj0OX75lIO
            VtV9OnOakIFV8NEqYDgwU7oHhBOSWVHVJGiygju0FplQpUr78qhjA6kI5OJF/7wI
            ASR/VxPhClLq7nZ/cvRm4xGaGBbY5sGNMfqR1OFlCvAPaj2GC3isoPTfYZOAn40L
            dQlClV0HdWpIj8ZqQgKjAvQj5Egaq0xRvUY40LU8sjbFECQuP8SO8iZ3hogUUJLB
            7atGqvm1ISAz4Xdlzfp8E/YpW/1g6oy+p04DhZkU0U1o62wxti6l6y8GVmy/aZUu
            Okre+iyE9/8olKolrdVDh+CMry3UgE2rA6GieLoDpNSF51E96VOYtsGyA2A73O9t
            lsisCKOKVf0qTjiPKqWkq9feXhM3wSUg6MloysGEc3UgsX1NiL1z4wjgN2tq6FTS
            XgEWX4pDAU0y4swz73GYcL/IiJAt/Xk58Fp/dLH8jYfpeAm3nGlnf4CtVvRZr9ta
            Y9JdEoF2rcxOSYIMlAgZHLRzE4ouK44JA6Z4ztUaKKSi5rbHtpeKjK6pJarBZtA=
            =o5+y
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    version: 3.13.3
