apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: lowrider-nav
    namespace: apps
stringData:
    ROUTERD_DATABASE_DSN: ENC[AES256_GCM,data:J61fuu5HnwCqTJlrjigLrOTN50wsEEIi+Bg1UWP8pKs45jxKTYf9yGKbjzRmLryHNBJ9A/QlDu+VUvVVrMYXIV5lR8XGcrYYhD373gR5hKE5guM9OS3Ku21f8e8kO94fbPT0eI8lyYnhDf5bl1LgrtecJI/nKtByS/ubBBOR6yNJEQ==,iv:MVgSbB4WQcOEDMuKy96aBSjyPnpWzhQNmmfaNeMK/Ns=,tag:BFZCInyeGHzlk+KBB34rDA==,type:str]
sops:
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-12T18:42:05Z"
    mac: ENC[AES256_GCM,data:Bsi1TFe+5Vsa52CVUUpPZE3aFKGuTtq94DNw+R8ln/2DSI8Gme5Sr1p0Il2gShqBo0xv21zdf83jVXCGImyXItNbhzZ1ymIBOjnwoCSmJB5NctUskdc93H+M5Znl/8Fa7a00YAChv58Q9eFi2xEyf25J6JyexFQJ5PhNe6tesXY=,iv:D4pXwkJZfBp/ewwKmb6nIFgfnOfSWhnuZaJJ8SfUphU=,tag:k/tpUXft9Bo95kDwSKIk/w==,type:str]
    pgp:
        - created_at: "2026-08-12T18:42:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ/+PR+8p293c3CfB94QFBB3nqEsbeyYtN++0RdXuZIfOImL
            XQzaAN6IcHDxtlfrpQrvUHUuxnDM+0LNR1vTp8XDfuFVRngXeRN7nz3zgcvsRzt4
            6cxGM3JCT+mrUSGNo/nlhBm9sZF1KUpXqOc/ugEwviK+mFHTPctqiOoHl3nrjB/h
            8+dqiKLURSEv7TgdUwTXiSbMTKBa0BiKBkoiCpboyysQG/gdqBkF5lM1rVfH8YnK
            IV+i/JCi8Dofun+WtssCAyMxEx1x/iesDx4fPUyQq+WspnkYIi+PoIW70bMCUw5s
            IRiWoDVW8TRGRIc0G3+q3WCj6w7BDSiX9DK3W1laOCnOpLHyhyEPB1GshqcfQcZX
            noVzPR+Lx1qKhy1yrlXDtphTEYfo+GEuxVlo1/+JRVovZ1OPKgDfz27RffhRRJ1N
            bwY8t53rhIajUa4yoGMZ6IN85k4Bl/Rv8ZesHLvUEYeZen3YwWl00YUDGLdqDAwi
            BCkhaqGgQyL0FzPLCRTBERiN1yrC0lKGNx7khzgtUp39h4S4vnLtKsaqvbWSx0UN
            REy7wDZ4GouNR0V6IOvIn87PeUIMtl7o7K5MTfhgqxiOH8787lyJiFpbKjAn8Cx3
            km9C2a5omCqVoAmYG3Nxw/yLmgSCOvYGqEYuYqbe4g6RsSsVpU145A3y+ohYO43S
            XAFCHaXA6KuXn86wmXzVC3az1PkkpjUyqdJEwLTg5ItIMADr2EeFw9EJFA1GiXQq
            Ik8PvO3GJgs+FfeTa9Ee7pLDGJr7iYheqFL7H2wQB6OWFOWIRlY6XZjw4ECl
            =CJpY
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    version: 3.13.3
