apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: ./deploy/helm
      sourceRef:
        kind: GitRepository
        name: synology-csi
  values:
    storageClasses:
      synology-csi-delete:
        parameters:
          fsType: btrfs
      synology-csi-retain:
        reclaimPolicy: Retain
        parameters:
          fsType: btrfs

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DaemonSet
              name: synology-csi-node
            patch: |
              - op: add
                path: /spec/template/metadata/annotations
                value:
                  secret.reloader.stakater.com/reload: client-info-secret
          - target:
              kind: StatefulSet
              name: synology-csi-controller
            patch: |
              - op: add
                path: /spec/template/metadata/annotations
                value:
                  secret.reloader.stakater.com/reload: client-info-secret
